Project D
unica-isde/isde-projects-2023-D pull request #7
Opened 2024-03-07 14:46 UTC by mohamednjah

Solved all issues

2024-03-26 11:31 UTC, asotgiu commented on app/ml/classification_utils.py
> +            shutil.copyfileobj(image_id.file, buffer)
What happens if multiple users upload files with the same name?

2024-03-26 11:35 UTC, asotgiu commented on app/ml/classification_utils.py
> +        print("Upload Error")
If something goes wrong (for instance, an invalid file is uploaded), the user does not know what happened as no error message is shown in the web interface.

2024-03-26 11:37 UTC, asotgiu commented on app/ml/classification_utils.py
> +            shutil.copyfileobj(image_id.file, buffer)
All uploaded files are stored and never removed, even if they are not valid images. This should be avoided as files may accumulate without any control of their content and memory usage.

2024-03-26 11:39 UTC, asotgiu commented on app/transformations/transfomation_utils.py
> +        enhanced_image.save(destination_path)
What happens if multiple users ask for the same job? The file would be overwritten. Isn't it best to return the results directly? Or, if you reuse them later for other things, another way to do it would be to store the results with a unique name and clean up after the response is returned to the user (or after a while anyway).

2024-03-26 11:40 UTC, asotgiu commented on main.py
> +        outfile.write(out)
What happens if multiple users ask for a classification job? The file would be overwritten. Isn't it best to return the results directly? Or, if you reuse them later for other things, another way to do it would be to store the results with a unique name and clean up after the response is returned to the user (or after a while anyway).

2024-03-26 11:41 UTC, asotgiu commented on main.py
> +        plt.savefig('app/static/output/png/img.png')
What happens if multiple users ask for a classification job? The file would be overwritten. Isn't it best to return the results directly? Or, if you reuse them later for other things, another way to do it would be to store the results with a unique name and clean up after the response is returned to the user (or after a while anyway).

2024-03-26 12:05 UTC, asotgiu requested changes
All the requested functionalities are correctly implemented, but a few things need to be addressed before approving and merging the PR:
- Please fix the file storage and concurrency problems (see comments).
- You added the image transformation functionality inside the classification webpage. However, it is confusing as a user might think the classification is performed on the transformed image. Please make it clearer, for instance, using two separate web pages for image classification of transformation or classifying the transformed image.
- Please add a changelog with the list of resolved issues to the pull request documentation (edit the description of the PR, or at least use the GUI functionality to link the PR to the issues of the target repository).

Request a new review when it's done. There's no need to open a new PR, it's enough to push the new commits to the origin repository (yours) of the PR. In that way, I will see only the new changes, and I won't have to review the full code again.
Thanks!

2024-04-16 08:29 UTC, asotgiu commented
Hello, it seems that after the first review some changes have been applied. If you are done, please request another review. Otherwise, I will assume that the PR is not ready for review.

2024-04-20 03:01 UTC, mohamednjah commented
Hello @asotgiu 
We have finished our changes to the repository and we are awaiting your review, thanks in advance.

2024-04-22 08:41 UTC, asotgiu approved these changes
All the requested changes have been implemented and the code looks good now, well done! I will merge the PR to the main repository.

2024-04-22 08:41 UTC, merged